baseURL = "https://ryandran.com"
disableLanguages = ["fr"]
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "20"
theme = "geeky-curious"
title = "Ryans Tech Blog"
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"
[imaging]
quality = 75
timeout = 180000
[markup.goldmark.extensions]
typographer = false
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false
[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = "--"
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = false
tabWidth = 2
unsafe = true
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[module.hugoVersion]
extended = true
min = "0.87.0"
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]
[permalinks]
blog = "/:slug/"
page = "/:slug/"
