about_widget_content = "Blog about Sofware Development, AI and Computer Vision."
address = "Johannesburg South Africa"
author = "Ryandran Naidoo"
buyMeACoffeeId = "vietanhdev"
codeLineNumbers = true
contact_form_action = "https://formspree.io/xaypalea"
copyright = "Copyright © 2022 Blog AICurious. All Rights Reserved."
description = "Blog about Tech.............mostly VMware"
email = "ryandran@gmail.com"
favicon = "images/favicon.png"
featured_post_title = "Featured Posts"
footer_content = "Blog about Sofware Development, AI and Computer Vision."
image = "images/logo.png"
logo = "images/logo.png"
logo_text = "Boilerplate"
logo_width = "220px"
mainSections = ["blog"]
navbar_fixed = false
recent_post_title = "Recent Posts"
search = true
social = []
talkyardScriptUrl = ""
talkyardServerUrl = ""
[advertisement]
image = "images/daisykit.png"
link = "/posts/2022-01-13-daisykit/"
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Know About Me"
button_link = "about/"
content = "Let's build AI-powered software! This blog writes about Sofware Development, AI and Computer Vision."
enable = true
image = "images/banner.png"
title_large = "Welcome **!**"
title_small = "to AICurious Blog"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = true
expire_days = 30
[preloader]
enable = false
preloader = ""
[subscription]
enable = false
mailchimp_form_action = ""
mailchimp_form_name = ""
[variables]
black = "#000"
body_color = "#FFF"
border_color = "#E1E1E1"
color_primary = "#0059ad"
light = "#f2f2f2"
text_color = "#051e50"
text_dark = "#00274f"
text_light = "#999"
white = "#FFF"
[widgets]
sidebar = ["about", "newsletter", "recent-post", "categories"]
